// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pleiades.Vault.Database;

#nullable disable

namespace plaintorch.Vault.Database.Migrations
{
    [DbContext(typeof(PlainfraContext))]
    [Migration("20260724170105_AddDependencySystem")]
    partial class AddDependencySystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Pleiades.Orchestration.Attentive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecreeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Estimation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolarisCycleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecreeId");

                    b.HasIndex("PolarisCycleId");

                    b.ToTable("Attentives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.CelestronTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePuck")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("CelestronLedger");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Checkpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CelestronToll")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ExternalCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TollPaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Dependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Constraint")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Satisfied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SourceRecurrenceDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("SourceRecurrenceTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TargetRecurrenceDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TargetRecurrenceTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Directive", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentDirectiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codename")
                        .IsUnique();

                    b.HasIndex("ParentDirectiveId");

                    b.ToTable("Directives");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Directive");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Pleiades.Orchestration.Eventive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Estimation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FateId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectiveId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RecurrenceDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("RecurrenceTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FateId");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("Eventives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Executive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AffinityTimeframeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Estimation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolarisCycleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AffinityTimeframeId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("PolarisCycleId");

                    b.ToTable("Executive");
                });

            modelBuilder.Entity("Pleiades.Orchestration.ExecutiveOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnrushSprintId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OnrushSprintId");

                    b.ToTable("ExecutiveOrders");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Incentive", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentIncentiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectiveId");

                    b.HasIndex("ParentIncentiveId");

                    b.ToTable("Incentives", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Incentive");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Pleiades.Orchestration.OnrushSprint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OnrushSprints");
                });

            modelBuilder.Entity("Pleiades.Orchestration.OrbitScheduleState", b =>
                {
                    b.Property<string>("IncentiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("IncentiveId");

                    b.ToTable("OrbitScheduleStates");
                });

            modelBuilder.Entity("Pleiades.Orchestration.PolarisCycle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PolarisCycles");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Reflective", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecreeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolarisCycleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecreeId");

                    b.HasIndex("PolarisCycleId");

                    b.ToTable("Reflective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.TagDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TagDefinitions");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Timeframe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectiveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orbit")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectiveId");

                    b.ToTable("Timeframes");
                });

            modelBuilder.Entity("Pleiades.Puck.PuckRegistryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Declaration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuckRegistryEntries");
                });

            modelBuilder.Entity("Pleiades.Puck.PuckSequence", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("NextValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("PuckSequences");
                });

            modelBuilder.Entity("Pleiades.Saga.LorePage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Puck");

                    b.Property<int?>("Act")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Beginning")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Era")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("IndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ParentPuck");

                    b.Property<int?>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("LoreIndexEntries");
                });

            modelBuilder.Entity("Pleiades.Vault.Database.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporalEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporalEntityTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporalEntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporalEntryKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporalKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporalLocation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("OccurredUtc");

                    b.HasIndex("SubjectType", "SubjectId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("Pleiades.Vault.Database.DatabaseGraveyardEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryKey")
                        .IsUnique();

                    b.ToTable("DatabaseGraveyardEntries");
                });

            modelBuilder.Entity("Pleiades.Vault.Database.FileGraveyardEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryKey")
                        .IsUnique();

                    b.ToTable("FileGraveyardEntries");
                });

            modelBuilder.Entity("Pleiades.Vault.Database.VaultMigrationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppliedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Conflicts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntitiesImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntitiesLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesRewritten")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MigrationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToVersion");

                    b.ToTable("VaultMigrationHistory");
                });

            modelBuilder.Entity("Pleiades.Orchestration.LunarDirective", b =>
                {
                    b.HasBaseType("Pleiades.Orchestration.Directive");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LunarStatus");

                    b.HasDiscriminator().HasValue("LunarDirective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.StellarDirective", b =>
                {
                    b.HasBaseType("Pleiades.Orchestration.Directive");

                    b.Property<DateOnly?>("Due")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.HasDiscriminator().HasValue("StellarDirective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Decree", b =>
                {
                    b.HasBaseType("Pleiades.Orchestration.Incentive");

                    b.Property<int>("ActiveCelestron")
                        .HasColumnType("INTEGER");

                    b.Property<int>("College")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Orbit")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Orbit");

                    b.Property<bool>("Reflect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DecreeStatus");

                    b.HasDiscriminator().HasValue("Decree");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Fate", b =>
                {
                    b.HasBaseType("Pleiades.Orchestration.Incentive");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Orbit")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Orbit");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FateStatus");

                    b.HasDiscriminator().HasValue("Fate");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Objective", b =>
                {
                    b.HasBaseType("Pleiades.Orchestration.Incentive");

                    b.Property<int>("CelestronValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Due")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnduring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnrushSprintId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("OnrushSprintId");

                    b.ToTable("Incentives", t =>
                        {
                            t.Property("College")
                                .HasColumnName("Objective_College");
                        });

                    b.HasDiscriminator().HasValue("Objective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Attentive", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Decree", "Decree")
                        .WithMany("Attentives")
                        .HasForeignKey("DecreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pleiades.Orchestration.PolarisCycle", "PolarisCycle")
                        .WithMany("Attentives")
                        .HasForeignKey("PolarisCycleId");

                    b.Navigation("Decree");

                    b.Navigation("PolarisCycle");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Directive", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Directive", "ParentDirective")
                        .WithMany("Subdirectives")
                        .HasForeignKey("ParentDirectiveId");

                    b.Navigation("ParentDirective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Eventive", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Fate", "Fate")
                        .WithMany("Eventives")
                        .HasForeignKey("FateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pleiades.Orchestration.Objective", "Objective")
                        .WithMany("Eventives")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Fate");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Executive", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Timeframe", "AffinityTimeframe")
                        .WithMany()
                        .HasForeignKey("AffinityTimeframeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pleiades.Orchestration.Objective", "Objective")
                        .WithMany("Executives")
                        .HasForeignKey("ObjectiveId");

                    b.HasOne("Pleiades.Orchestration.PolarisCycle", "PolarisCycle")
                        .WithMany("Executives")
                        .HasForeignKey("PolarisCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffinityTimeframe");

                    b.Navigation("Objective");

                    b.Navigation("PolarisCycle");
                });

            modelBuilder.Entity("Pleiades.Orchestration.ExecutiveOrder", b =>
                {
                    b.HasOne("Pleiades.Orchestration.OnrushSprint", "OnrushSprint")
                        .WithMany("ExecutiveOrders")
                        .HasForeignKey("OnrushSprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnrushSprint");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Incentive", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Directive", "Directive")
                        .WithMany("Incentives")
                        .HasForeignKey("DirectiveId");

                    b.HasOne("Pleiades.Orchestration.Incentive", "ParentIncentive")
                        .WithMany("ChildIncentives")
                        .HasForeignKey("ParentIncentiveId");

                    b.Navigation("Directive");

                    b.Navigation("ParentIncentive");
                });

            modelBuilder.Entity("Pleiades.Orchestration.OrbitScheduleState", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Incentive", "Incentive")
                        .WithMany()
                        .HasForeignKey("IncentiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incentive");
                });

            modelBuilder.Entity("Pleiades.Orchestration.PolarisCycle", b =>
                {
                    b.OwnsOne("Pleiades.Orchestration.PolarisForecast", "Forecast", b1 =>
                        {
                            b1.Property<string>("PolarisCycleId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("ForecastReference")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ForecastTarget")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PolarisCycleId");

                            b1.ToTable("PolarisCycles");

                            b1.WithOwner()
                                .HasForeignKey("PolarisCycleId");
                        });

                    b.Navigation("Forecast");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Reflective", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Decree", "Decree")
                        .WithMany("Reflectives")
                        .HasForeignKey("DecreeId");

                    b.HasOne("Pleiades.Orchestration.PolarisCycle", "PolarisCycle")
                        .WithMany("Reflectives")
                        .HasForeignKey("PolarisCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decree");

                    b.Navigation("PolarisCycle");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Timeframe", b =>
                {
                    b.HasOne("Pleiades.Orchestration.LunarDirective", "Directive")
                        .WithMany("Timeframes")
                        .HasForeignKey("DirectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directive");
                });

            modelBuilder.Entity("Pleiades.Saga.LorePage", b =>
                {
                    b.HasOne("Pleiades.Saga.LorePage", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Objective", b =>
                {
                    b.HasOne("Pleiades.Orchestration.OnrushSprint", "OnrushSprint")
                        .WithMany("Objectives")
                        .HasForeignKey("OnrushSprintId");

                    b.Navigation("OnrushSprint");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Directive", b =>
                {
                    b.Navigation("Incentives");

                    b.Navigation("Subdirectives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Incentive", b =>
                {
                    b.Navigation("ChildIncentives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.OnrushSprint", b =>
                {
                    b.Navigation("ExecutiveOrders");

                    b.Navigation("Objectives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.PolarisCycle", b =>
                {
                    b.Navigation("Attentives");

                    b.Navigation("Executives");

                    b.Navigation("Reflectives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.LunarDirective", b =>
                {
                    b.Navigation("Timeframes");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Decree", b =>
                {
                    b.Navigation("Attentives");

                    b.Navigation("Reflectives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Fate", b =>
                {
                    b.Navigation("Eventives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Objective", b =>
                {
                    b.Navigation("Eventives");

                    b.Navigation("Executives");
                });
#pragma warning restore 612, 618
        }
    }
}
