// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pleiades.Vault.Database;

#nullable disable

namespace plaintorch.Vault.Database.Migrations
{
    [DbContext(typeof(PlainfraContext))]
    [Migration("20260508173237_EnduringObjectivesAndExecutiveTitles")]
    partial class EnduringObjectivesAndExecutiveTitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Pleiades.Orchestration.CelestronTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePuck")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("CelestronLedger");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Directive", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeLoreDirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codename")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Due")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentDirectiveId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codename")
                        .IsUnique();

                    b.HasIndex("ParentDirectiveId");

                    b.ToTable("Directives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Executive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolarisCycleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("PolarisCycleId");

                    b.ToTable("Executive");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Objective", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CelestronValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectiveId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnduring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnrushSprintId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectiveId");

                    b.HasIndex("OnrushSprintId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.OnrushSprint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OnrushSprints");
                });

            modelBuilder.Entity("Pleiades.Orchestration.PolarisCycle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PolarisCycles");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Reflective", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolarisCycleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolarisCycleId");

                    b.ToTable("Reflective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.TagDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TagDefinitions");
                });

            modelBuilder.Entity("Pleiades.Puck.PuckRegistryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Declaration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuckRegistryEntries");
                });

            modelBuilder.Entity("Pleiades.Puck.PuckSequence", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("NextValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("PuckSequences");
                });

            modelBuilder.Entity("Pleiades.Vault.Database.LoreIndexEntry", b =>
                {
                    b.Property<string>("Puck")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Act")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Era")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("IndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPuck")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Puck");

                    b.ToTable("LoreIndexEntries");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Directive", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Directive", "ParentDirective")
                        .WithMany("Subdirectives")
                        .HasForeignKey("ParentDirectiveId");

                    b.Navigation("ParentDirective");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Executive", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Objective", "Objective")
                        .WithMany("Executives")
                        .HasForeignKey("ObjectiveId");

                    b.HasOne("Pleiades.Orchestration.PolarisCycle", "PolarisCycle")
                        .WithMany("Executives")
                        .HasForeignKey("PolarisCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");

                    b.Navigation("PolarisCycle");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Objective", b =>
                {
                    b.HasOne("Pleiades.Orchestration.Directive", "Directive")
                        .WithMany("Objectives")
                        .HasForeignKey("DirectiveId");

                    b.HasOne("Pleiades.Orchestration.OnrushSprint", "OnrushSprint")
                        .WithMany("Objectives")
                        .HasForeignKey("OnrushSprintId");

                    b.Navigation("Directive");

                    b.Navigation("OnrushSprint");
                });

            modelBuilder.Entity("Pleiades.Orchestration.PolarisCycle", b =>
                {
                    b.OwnsOne("Pleiades.Orchestration.PolarisForecast", "Forecast", b1 =>
                        {
                            b1.Property<string>("PolarisCycleId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("ForecastReference")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ForecastTarget")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PolarisCycleId");

                            b1.ToTable("PolarisCycles");

                            b1.WithOwner()
                                .HasForeignKey("PolarisCycleId");
                        });

                    b.Navigation("Forecast");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Reflective", b =>
                {
                    b.HasOne("Pleiades.Orchestration.PolarisCycle", "PolarisCycle")
                        .WithMany("Reflectives")
                        .HasForeignKey("PolarisCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolarisCycle");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Directive", b =>
                {
                    b.Navigation("Objectives");

                    b.Navigation("Subdirectives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.Objective", b =>
                {
                    b.Navigation("Executives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.OnrushSprint", b =>
                {
                    b.Navigation("Objectives");
                });

            modelBuilder.Entity("Pleiades.Orchestration.PolarisCycle", b =>
                {
                    b.Navigation("Executives");

                    b.Navigation("Reflectives");
                });
#pragma warning restore 612, 618
        }
    }
}
