using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Pleiades.Plaintorch.Api.Abstractions;
using Pleiades.Tests.Harness;
using Xunit;

namespace Pleiades.Tests.Core;

/// <summary>
/// The startup auto-generated-PUCK consistency pass keeps its legitimate authority inside granted territory:
/// a stray file carrying an unknown, notation-valid PUCK prefix is normalized (stripped to a title-only pre-PUCK
/// input) inside an auto-assign root or a known directive's folder, and an enforced root still purges non-entity
/// files. These guards pin that authority so the non-entity isolation fix (see
/// <see cref="NonEntityFileIsolationTests"/>) is proven surgical — confining the pass to its territory without
/// neutering it.
/// </summary>
public sealed class AutoGeneratedPuckConsistencyTests : VaultTestBase
{
	private Task<int> IncentiveCountAsync()
		=> Vault.QueryAsync(context => context.Incentives.CountAsync(TestContext.Current.CancellationToken));

	[Fact]
	public async Task A_desynced_prefixed_file_in_the_standalone_root_is_stripped_to_title_only()
	{
		// An unknown but notation-valid objective id in the granted Objectives root: a desynced entity file, which
		// the consistency pass normalizes back to a title-only pre-PUCK input.
		Vault.WriteVaultFile("Objectives/j00000099 - Foo.md", "# Foo" + Environment.NewLine + "body" + Environment.NewLine);

		await Vault.StartupSweepAsync();

		Assert.False(Vault.VaultFileExists("Objectives/j00000099 - Foo.md"));
		Assert.True(Vault.VaultFileExists("Objectives/Foo.md"));
		Assert.Equal(0, await IncentiveCountAsync());
	}

	[Fact]
	public async Task A_desynced_prefixed_file_in_a_known_directive_folder_is_stripped_to_title_only()
	{
		var directive = await Vault.WithScopeAsync(services => services
			.GetRequiredService<IDirectiveApi>()
			.CreateStandaloneAsync("Campaign", cancellationToken: TestContext.Current.CancellationToken));

		// A desynced objective file hosted inside a real (database-known) directive's partition.
		Vault.WriteVaultFile("Directives/Campaign/Objectives/j00000099 - Foo.md", "# Foo" + Environment.NewLine + "body" + Environment.NewLine);

		await Vault.StartupSweepAsync();

		Assert.False(Vault.VaultFileExists("Directives/Campaign/Objectives/j00000099 - Foo.md"));
		Assert.True(Vault.VaultFileExists("Directives/Campaign/Objectives/Foo.md"));
		Assert.Equal(0, await IncentiveCountAsync());
	}

	[Fact]
	public async Task An_enforced_root_still_purges_a_non_entity_file()
	{
		// The Journal root is enforced (granted) territory: a non-entity note there is purged to the graveyard,
		// keeping the root a clean outward interface for the database.
		Vault.WriteVaultFile("Journal/2026-09-06 - Notes.md", "# Notes" + Environment.NewLine + "body" + Environment.NewLine);

		await Vault.StartupSweepAsync();

		Assert.False(Vault.VaultFileExists("Journal/2026-09-06 - Notes.md"));
	}
}
