namespace Pleiades.Vault.Markdown;

/// <summary>
/// Summarizes consistency actions applied to auto-generated-PUCK markdown files.
/// </summary>
public sealed record VaultAutoGeneratedPuckConsistencyResult(
	int FilesScanned,
	int FilesPurged,
	int FilesRenamed,
	int FilesAlreadyTitleOnly);