using Pleiades.Orchestration;
using Pleiades.Puck;
using Pleiades.Vault;
using Pleiades.Vault.Database;
using Pleiades.Vault.Markdown;

namespace Pleiades.Plaintorch;

/// <summary>
/// Coordinates high-level PLAINTORCH operations across vault, markdown, persistence, and PUCK services.
/// </summary>
public sealed class PlaintorchEngine(
	VaultBootstrapper bootstrapper,
	PlaintorchRepository repository,
	LoreIndexer loreIndexer,
	VaultAutoGeneratedPuckConsistencyService autoGeneratedPuckConsistencyService,
	PuckCreationService puckCreationService,
	PolarisCycleLifecycle polarisCycleLifecycle,
	MarkdownFrontMatterSerializer markdownSerializer,
	MarkdownFileLocator markdownFileLocator)
{
	/// <summary>
	/// Initializes the vault directory structure and backing database.
	/// </summary>
	public void InitializeVault()
	{
		bootstrapper.Initialize();
		autoGeneratedPuckConsistencyService.ReconcileAsync().GetAwaiter().GetResult();
		loreIndexer.RebuildIndex();
	}

	/// <summary>
	/// Initializes the vault directory structure and backing database.
	/// </summary>
	public async Task InitializeVaultAsync(CancellationToken cancellationToken = default)
	{
		await bootstrapper.InitializeAsync(cancellationToken);
		await autoGeneratedPuckConsistencyService.ReconcileAsync(cancellationToken);
		await loreIndexer.RebuildIndexAsync(cancellationToken);
	}

	/// <summary>
	/// Rebuilds the saga lore index from file-first markdown content.
	/// </summary>
	/// <returns>The number of indexed lore entries.</returns>
	public int ReindexLore() => loreIndexer.RebuildIndex();

	/// <summary>
	/// Rebuilds the saga lore index from file-first markdown content.
	/// </summary>
	/// <returns>The number of indexed lore entries.</returns>
	public Task<int> ReindexLoreAsync(CancellationToken cancellationToken = default) => loreIndexer.RebuildIndexAsync(cancellationToken);

	/// <summary>
	/// Creates and persists a new directive.
	/// </summary>
	public Directive CreateDirective(string title, string? parentDirectiveId = null)
	{
		var parentDirective = string.IsNullOrWhiteSpace(parentDirectiveId)
			? null
			: repository.GetDirective(parentDirectiveId);

		var directive = new Directive
		{
			Id = puckCreationService.CreateIdFor<Directive>(),
			Title = title,
			ParentDirectiveId = parentDirectiveId,
		};
		repository.UpsertDirective(directive);
		WriteVaultMarkdown(directive, markdownSerializer.Serialize(directive, $"# {directive.Title}"), parentDirective: parentDirective);
		return directive;
	}

	/// <summary>
	/// Defines a reusable tag and associates it with a semantic color.
	/// </summary>
	public TagDefinition DefineTag(string id, string title, TagColor color = TagColor.Light, string? description = null)
	{
		var tagDefinition = new TagDefinition
		{
			Id = id,
			Title = title,
			Color = color,
			Description = description,
		};

		repository.UpsertTagDefinition(tagDefinition);
		return tagDefinition;
	}

	/// <summary>
	/// Creates and persists a new onrush sprint.
	/// </summary>
	public OnrushSprint CreateOnrushSprint(string title, DateOnly? startDate = null)
	{
		var sprintDate = startDate ?? DateOnly.FromDateTime(DateTime.UtcNow);
		var sprint = new OnrushSprint
		{
			Id = puckCreationService.CreateIdFor<OnrushSprint>(systemSegments: [new PuckSegmentInput(Date: sprintDate)]),
			Title = title,
			StartDate = startDate,
		};
		repository.UpsertOnrushSprint(sprint);
		WriteVaultMarkdown(sprint, markdownSerializer.Serialize(sprint, $"# {sprint.Title}"));
		return sprint;
	}

	/// <summary>
	/// Persists a Polaris cycle and emits its markdown representation.
	/// </summary>
	public PolarisCycle SavePolarisCycle(PolarisCycle cycle, string? body = null)
	{
		ArgumentNullException.ThrowIfNull(cycle);
		if (string.IsNullOrWhiteSpace(cycle.Id))
		{
			throw new InvalidOperationException("Polaris cycles must receive a PUCK-managed identifier before persistence.");
		}

		if (string.IsNullOrWhiteSpace(cycle.Title))
		{
			cycle.Title = $"Polaris Cycle {cycle.Id}";
		}

		repository.UpsertPolarisCycle(cycle);
		WriteVaultMarkdown(cycle, markdownSerializer.Serialize(cycle, body ?? $"# {cycle.Title}"));
		return cycle;
	}

	/// <summary>
	/// Plans, persists, and emits a new Polaris forecast cycle using a centrally issued PUCK identifier.
	/// </summary>
	/// <param name="forecastReference">The reference date from which the forecast is computed.</param>
	/// <param name="daysAhead">The forecast horizon in days.</param>
	/// <param name="body">Optional markdown body content.</param>
	/// <returns>The persisted Polaris cycle.</returns>
	public PolarisCycle PlanPolarisForecast(DateOnly forecastReference, int daysAhead, string? body = null)
	{
		var targetDate = forecastReference.AddDays(daysAhead);
		var id = puckCreationService.CreateIdFor<PolarisCycle>(systemSegments: [new PuckSegmentInput(Date: targetDate)]);
		var cycle = polarisCycleLifecycle.PlanForecast(forecastReference, daysAhead, id);
		return SavePolarisCycle(cycle, body ?? "# Forecast");
	}

	/// <summary>
	/// Persists an objective without generating a new identifier.
	/// </summary>
	public Objective SaveObjective(Objective objective)
	{
		ArgumentNullException.ThrowIfNull(objective);
		if (string.IsNullOrWhiteSpace(objective.Id))
		{
			objective.Id = puckCreationService.CreateIdFor<Objective>();
		}

		repository.UpsertObjective(objective);
		WriteVaultMarkdown(objective, markdownSerializer.Serialize(objective, $"# {objective.Title}"), objectiveDirective: string.IsNullOrWhiteSpace(objective.DirectiveId) ? null : repository.GetDirective(objective.DirectiveId));
		return objective;
	}

	/// <summary>
	/// Creates and persists a new objective.
	/// </summary>
	public Objective CreateObjective(string title, string? directiveId = null, string? onrushSprintId = null)
	{
		var objective = new Objective
		{
			Id = puckCreationService.CreateIdFor<Objective>(),
			Title = title,
			DirectiveId = directiveId,
			OnrushSprintId = onrushSprintId,
		};
		repository.UpsertObjective(objective);
		WriteVaultMarkdown(objective, markdownSerializer.Serialize(objective, $"# {objective.Title}"), objectiveDirective: string.IsNullOrWhiteSpace(directiveId) ? null : repository.GetDirective(directiveId));
		return objective;
	}

	/// <summary>
	/// Adds an execution record to a Polaris cycle.
	/// </summary>
	public long AddExecutive(Executive executive) => repository.AddExecutive(executive);

	/// <summary>
	/// Adds a reflective record to a Polaris cycle.
	/// </summary>
	public long AddReflective(Reflective reflective) => repository.AddReflective(reflective);

	/// <summary>
	/// Records a Celestron ledger transaction.
	/// </summary>
	public void RecordCelestronTransaction(CelestronTransaction transaction) => repository.AddCelestronTransaction(transaction);

	/// <summary>
	/// Gets a compact status string summarizing stored entity counts.
	/// </summary>
	public string GetStatusReport()
	{
		var counts = repository.GetCounts();
		return $"Directives={counts.Directives}, Objectives={counts.Objectives}, OnrushSprints={counts.Sprints}, PolarisCycles={counts.Cycles}, Executives={counts.Executives}, Reflectives={counts.Reflectives}, CelestronTransactions={counts.Transactions}, TagDefinitions={counts.Tags}, LoreEntries={counts.LoreEntries}";
	}

	/// <summary>
	/// Writes markdown content to a target path, creating parent directories when needed.
	/// </summary>
	private static void WriteMarkdown(string path, string markdown)
	{
		Directory.CreateDirectory(Path.GetDirectoryName(path)!);
		File.WriteAllText(path, markdown);
	}

	private void WriteVaultMarkdown(object entity, string markdown, Directive? parentDirective = null, Directive? objectiveDirective = null)
	{
		if (!MarkdownFileLocator.HasFileBacking(entity.GetType()))
		{
			return;
		}

		var path = entity switch
		{
			Directive directive => markdownFileLocator.GetDirectiveFilePath(directive, parentDirective),
			Objective objective => markdownFileLocator.GetObjectiveFilePath(objective, objectiveDirective),
			_ => markdownFileLocator.GetFilePath(entity),
		};

		WriteMarkdown(path, markdown);
	}
}