using Pleiades.Plaintorch.Markdown;
using Pleiades.Plaintorch.Preferences;
using Pleiades.Vault;
using Pleiades.Vault.Database;
using Pleiades.Vault.Markdown;
using Pleiades.Vault.Migration;

namespace Pleiades.Plaintorch;

/// <summary>
/// Coordinates vault activation: bootstrapping the directory structure and database, running migrations, draining any
/// pending vault writes, reconciling auto-generated PUCKs, and loading user preferences. Entity mutation lives in the
/// API services, which write through the vault write queue (PEP110 Refactor BETA) — the engine holds no file writer.
/// </summary>
public sealed class PlaintorchEngine(
	VaultBootstrapper bootstrapper,
	PlaintorchRepository repository,
	VaultMigrationRunner vaultMigrationRunner,
	VaultAutoGeneratedPuckConsistencyService autoGeneratedPuckConsistencyService,
	VaultWriteQueue writeQueue,
	UserPreferenceService userPreferenceService)
{
	/// <summary>
	/// Initializes the vault directory structure and backing database.
	/// </summary>
	public void InitializeVault()
	{
		bootstrapper.Initialize();
		vaultMigrationRunner.RunAsync().GetAwaiter().GetResult();
		writeQueue.DrainPendingAsync().GetAwaiter().GetResult();
		autoGeneratedPuckConsistencyService.ReconcileAsync().GetAwaiter().GetResult();
		userPreferenceService.LoadAsync().GetAwaiter().GetResult();
	}

	/// <summary>
	/// Initializes the vault directory structure and backing database.
	/// </summary>
	public async Task InitializeVaultAsync(CancellationToken cancellationToken = default)
	{
		await bootstrapper.InitializeAsync(cancellationToken);
		await vaultMigrationRunner.RunAsync(cancellationToken);
		// Recover any write intent a crash left between the database commit and the file write (PEP110 Refactor BETA),
		// so half-written entities are materialized before the file->database consistency passes run.
		await writeQueue.DrainPendingAsync(cancellationToken);
		await autoGeneratedPuckConsistencyService.ReconcileAsync(cancellationToken);
		await userPreferenceService.LoadAsync(cancellationToken);
	}

	/// <summary>
	/// Gets a compact status string summarizing stored entity counts.
	/// </summary>
	public string GetStatusReport()
	{
		var counts = repository.GetCounts();
		return $"Directives={counts.Directives}, Objectives={counts.Objectives}, OnrushSprints={counts.Sprints}, PolarisCycles={counts.Cycles}, Executives={counts.Executives}, Reflectives={counts.Reflectives}, CelestronTransactions={counts.Transactions}, TagDefinitions={counts.Tags}, LoreEntries={counts.LoreEntries}";
	}
}
