using Microsoft.EntityFrameworkCore;
using Pleiades.Plaintorch.Markdown;
using Pleiades.Plaintorch.Materialization;
using Pleiades.Plaintorch.Preferences;
using Pleiades.Vault;
using Pleiades.Vault.Database;
using Pleiades.Vault.Markdown;
using Pleiades.Vault.Migration;

namespace Pleiades.Plaintorch;

/// <summary>
/// Coordinates vault activation: bootstrapping the directory structure and database, running migrations, draining any
/// pending vault writes, reconciling auto-generated PUCKs, loading user preferences, and warming the active Polaris
/// cycle's timeframe candidates. Entity mutation lives in the API services, which write through the vault write queue
/// (PEP110 Refactor BETA) — the engine holds no file writer.
/// </summary>
public sealed class PlaintorchEngine(
	VaultBootstrapper bootstrapper,
	PlaintorchRepository repository,
	VaultMigrationRunner vaultMigrationRunner,
	VaultAutoGeneratedPuckConsistencyService autoGeneratedPuckConsistencyService,
	VaultWriteQueue writeQueue,
	UserPreferenceService userPreferenceService,
	TimeframeCandidateCache timeframeCandidateCache,
	IServiceScopeFactory scopeFactory,
	ILogger<PlaintorchEngine> logger)
{
	/// <summary>
	/// Initializes the vault directory structure and backing database.
	/// </summary>
	public void InitializeVault()
	{
		bootstrapper.Initialize();
		vaultMigrationRunner.RunAsync().GetAwaiter().GetResult();
		writeQueue.DrainPendingAsync().GetAwaiter().GetResult();
		autoGeneratedPuckConsistencyService.ReconcileAsync().GetAwaiter().GetResult();
		userPreferenceService.LoadAsync().GetAwaiter().GetResult();
		WarmTimeframeCandidatesAsync().GetAwaiter().GetResult();
	}

	/// <summary>
	/// Initializes the vault directory structure and backing database.
	/// </summary>
	public async Task InitializeVaultAsync(CancellationToken cancellationToken = default)
	{
		await bootstrapper.InitializeAsync(cancellationToken);
		await vaultMigrationRunner.RunAsync(cancellationToken);
		// Recover any write intent a crash left between the database commit and the file write (PEP110 Refactor BETA),
		// so half-written entities are materialized before the file->database consistency passes run.
		await writeQueue.DrainPendingAsync(cancellationToken);
		await autoGeneratedPuckConsistencyService.ReconcileAsync(cancellationToken);
		await userPreferenceService.LoadAsync(cancellationToken);
		await WarmTimeframeCandidatesAsync(cancellationToken);
	}

	/// <summary>
	/// Gets a compact status string summarizing stored entity counts.
	/// </summary>
	public string GetStatusReport()
	{
		var counts = repository.GetCounts();
		return $"Directives={counts.Directives}, Objectives={counts.Objectives}, OnrushSprints={counts.Sprints}, PolarisCycles={counts.Cycles}, Executives={counts.Executives}, Reflectives={counts.Reflectives}, CelestronTransactions={counts.Transactions}, TagDefinitions={counts.Tags}, LoreEntries={counts.LoreEntries}";
	}

	/// <summary>
	/// Purges any previous session's timeframe candidates and, when a Polaris cycle had already begun (strictly
	/// active: started and not ended) before this activation, warms its candidates (PEP100 patch 2). Runs after the
	/// preferences load, since the default calendar decides how timeframe orbits read.
	/// </summary>
	/// <remarks>
	/// The warm is best effort: the candidate listing recomputes lazily on a miss, so a failure is logged as a warning
	/// and never aborts vault activation. Cancellation still propagates.
	/// </remarks>
	private async Task WarmTimeframeCandidatesAsync(CancellationToken cancellationToken = default)
	{
		timeframeCandidateCache.Purge();

		try
		{
			// A fresh scope: this activation scope may already have read the calendar preference before it was loaded,
			// and its options snapshot would keep that stale value.
			using var scope = scopeFactory.CreateScope();
			var context = scope.ServiceProvider.GetRequiredService<PlainfraContext>();
			var activeCycle = await context.PolarisCycles
				.AsNoTracking()
				.Where(cycle => cycle.StartTime != null && cycle.EndTime == null)
				.OrderByDescending(cycle => cycle.Id)
				.FirstOrDefaultAsync(cancellationToken);
			if (activeCycle is not null)
			{
				await scope.ServiceProvider.GetRequiredService<TimeframeCandidateService>().RefreshAsync(activeCycle, cancellationToken);
			}
		}
		catch (Exception exception) when (exception is not OperationCanceledException)
		{
			logger.LogWarning(exception, "PLAINTORCH could not warm the active Polaris cycle's timeframe candidates at vault activation; they will be computed on first read.");
		}
	}
}
