using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Pleiades.Orchestration;
using Pleiades.Puck;
using Pleiades.Plaintorch.State;
using Pleiades.Vault;
using Pleiades.Vault.Database;
using Pleiades.Vault.Markdown;
using Pleiades.Vault.Migration;
using Pleiades.Vault.Migration.Migrations;
using Pleiades.Vault.Policy;
using Pleiades.Vault.Watcher;

namespace Pleiades.Plaintorch;

/// <summary>
/// Registers the current PLAINTORCH application services through the A11d module pipeline.
/// </summary>
public sealed class PlaintorchModule : Module
{
	/// <inheritdoc />
	public override void ConfigureServices(IServiceCollection services)
	{
		services.TryAddSingleton(_ => PlaintorchUserLayout.CreateDefault());
		services.AddSingleton<PlaintorchUserConfigurationStore>();
		services.AddSingleton<PlaintorchVaultActivationService>();
		services.AddSingleton<VaultLayout>();
		services.AddScoped<PlaintorchStatePolicyProcessor>();
		services.AddScoped<PlaintorchStatePolicyFileSyncService>();
		services.AddScoped<PlaintorchStatePolicyInterceptor>();
		services.AddDbContext<PlainfraContext>((serviceProvider, options) =>
		{
			var layout = serviceProvider.GetRequiredService<VaultLayout>();
			Directory.CreateDirectory(layout.MetadataRoot);
			options.UseSqlite($"Data Source={layout.DatabasePath}");
			options.AddInterceptors(serviceProvider.GetRequiredService<PlaintorchStatePolicyInterceptor>());
		});

		services.AddScoped<PlainfraContextInitializer>();
		services.AddScoped<VaultBootstrapper>();
		services.AddScoped<PlaintorchRepository>();
		services.AddScoped<VaultTemporalDataService>();
		services.AddScoped<VaultAuditLogService>();
		services.AddScoped<VaultImplicitBoundaryService>();
		services.AddSingleton<PuckNotationParser>();
		services.AddSingleton<PuckRuntimeCompilationCatalog>();
		services.AddSingleton<VaultEntityModelCatalog>();
		services.AddScoped<VaultEntityGateway>();
		services.AddSingleton<PuckTokenizer>();
		services.AddSingleton<PuckPathDiscriminabilityService>();
		services.AddSingleton<PuckSemanticProjector>();
		services.AddScoped<PuckEntityResolutionService>();
		services.AddScoped<PuckCreationService>();
		services.AddScoped<LoreIndexer>();
		services.AddScoped<PuckIdService>();
		services.AddSingleton<PolarisCycleLifecycle>();
		services.AddSingleton<MarkdownFrontMatterSerializer>();
		services.AddSingleton<MarkdownFileLocator>();
		services.AddSingleton<VaultPathSyncModelCatalog>();
		services.AddSingleton<VaultWatcherPathPolicy>();
		services.AddSingleton<VaultWatcherIssueRegistry>();
		services.AddSingleton<VaultWatcherWriteBarrier>();
		services.AddSingleton<VaultStorageTopologyValidator>();
		services.AddSingleton<PlaintorchVaultLockService>();
		services.AddSingleton<PlaintorchCoreSplashService>();
		services.AddSingleton<PlaintorchServiceBootstrapper>();
		services.AddScoped<IVaultStorageModePolicyService, FreeformVaultStorageModePolicyService>();
		services.AddScoped<IVaultStorageModePolicyService, ImplicitVaultStorageModePolicyService>();
		services.AddScoped<IVaultStorageModePolicyService, EnforcedVaultStorageModePolicyService>();
		services.AddScoped<IVaultStorageModePolicyService, OptionalVaultStorageModePolicyService>();
		services.AddScoped<IVaultStorageModePolicyService, SyncedVaultStorageModePolicyService>();
		services.AddScoped<IVaultStorageModePolicyService, FileFirstVaultStorageModePolicyService>();
		services.AddScoped<VaultStorageModePolicyRouter>();
		services.AddScoped<VaultStoragePolicyEngine>();
		services.AddScoped<VaultSyncDecisionService>();
		services.AddScoped<VaultMarkdownDiscoveryService>();
		services.AddScoped<VaultWatcherSyncService>();
		services.AddScoped<VaultAutoGeneratedPuckConsistencyService>();
		services.AddSingleton<VaultVersionService>();
		services.AddScoped<VaultConventionSetFactory>();
		services.AddScoped<VaultLoader>();
		services.AddScoped<VaultMigrationRunner>();
		services.AddScoped<IVaultMigration, ObjectiveQuietCanonicalizationMigration>();
		services.AddScoped<PlaintorchEngine>();
		services.AddHostedService<PlaintorchCoreService>();
		services.AddHostedService<VaultWatcherService>();
	}

	/// <inheritdoc />
	public override void ConfigureApplication(WebApplication application)
	{
	}

	/// <inheritdoc />
	public override void ConfigureEndpoints(IEndpointRouteBuilder endpoints)
	{
	}
}