using Microsoft.EntityFrameworkCore;
using Pleiades.Orchestration;
using Pleiades.Puck;
using Pleiades.Plaintorch.State;
using Pleiades.Vault;
using Pleiades.Vault.Database;
using Pleiades.Vault.Markdown;
using Pleiades.Vault.Watcher;

namespace Pleiades.Plaintorch;

/// <summary>
/// Registers the current PLAINTORCH application services through the A11d module pipeline.
/// </summary>
public sealed class PlaintorchModule : Module
{
	/// <inheritdoc />
	public override void ConfigureServices(IServiceCollection services)
	{
		services.AddSingleton(PlaintorchUserLayout.CreateDefault());
		services.AddSingleton<PlaintorchUserConfigurationStore>();
		services.AddSingleton<PlaintorchVaultActivationService>();
		services.AddSingleton<VaultLayout>();
		services.AddScoped<PlaintorchStatePolicyProcessor>();
		services.AddScoped<PlaintorchStatePolicyFileSyncService>();
		services.AddScoped<PlaintorchStatePolicyInterceptor>();
		services.AddDbContext<PlainfraContext>((serviceProvider, options) =>
		{
			var layout = serviceProvider.GetRequiredService<VaultLayout>();
			Directory.CreateDirectory(layout.MetadataRoot);
			options.UseSqlite($"Data Source={layout.DatabasePath}");
			options.AddInterceptors(serviceProvider.GetRequiredService<PlaintorchStatePolicyInterceptor>());
		});

		services.AddScoped<PlainfraContextInitializer>();
		services.AddScoped<VaultBootstrapper>();
		services.AddScoped<PlaintorchRepository>();
		services.AddScoped<VaultTemporalDataService>();
		services.AddScoped<VaultAuditLogService>();
		services.AddSingleton<PuckNotationParser>();
		services.AddSingleton<PuckTokenizer>();
		services.AddSingleton<PuckPathDiscriminabilityService>();
		services.AddSingleton<PuckSemanticProjector>();
		services.AddScoped<PuckCreationService>();
		services.AddScoped<LoreIndexer>();
		services.AddScoped<PuckIdService>();
		services.AddSingleton<PolarisCycleLifecycle>();
		services.AddSingleton<MarkdownFrontMatterSerializer>();
		services.AddSingleton<MarkdownFileLocator>();
		services.AddSingleton<VaultPathSyncModelCatalog>();
		services.AddSingleton<VaultWatcherWriteBarrier>();
		services.AddSingleton<VaultStorageTopologyValidator>();
		services.AddSingleton<PlaintorchVaultLockService>();
		services.AddSingleton<PlaintorchCoreSplashService>();
		services.AddSingleton<PlaintorchServiceBootstrapper>();
		services.AddScoped<VaultSyncDecisionService>();
		services.AddScoped<VaultMarkdownDiscoveryService>();
		services.AddScoped<VaultWatcherSyncService>();
		services.AddScoped<VaultAutoGeneratedPuckConsistencyService>();
		services.AddScoped<PlaintorchEngine>();
		services.AddHostedService<PlaintorchCoreService>();
		services.AddHostedService<VaultWatcherService>();
	}

	/// <inheritdoc />
	public override void ConfigureApplication(WebApplication application)
	{
	}

	/// <inheritdoc />
	public override void ConfigureEndpoints(IEndpointRouteBuilder endpoints)
	{
	}
}