using System.Reflection;
using Pleiades.Orchestration;
using Pleiades.Puck;
using Pleiades.Saga;
using Pleiades.Vault.Database;
using Pleiades.Vault.Policy;
using Pleiades.Vault.Watcher;

namespace Pleiades.Vault.Markdown;

/// <summary>
/// Reconciles vault-backed markdown files for entities whose PUCK identifiers are generated by the core.
/// </summary>
public sealed class VaultAutoGeneratedPuckConsistencyService(
	PlainfraContext context,
	VaultLayout layout,
	VaultPathSyncModelCatalog pathSyncModelCatalog,
	VaultEntityModelCatalog entityModelCatalog,
	MarkdownFrontMatterSerializer markdownSerializer,
	VaultTemporalDataService temporalDataService,
	VaultAuditLogService auditLogService,
	VaultStoragePolicyEngine policyEngine,
	PuckIdentityGate identityGate,
	VaultWatcherPathPolicy pathPolicy)
{
	/// <summary>
	/// Ensures stray user-created or desynchronized files are normalized according to the current storage policy.
	/// </summary>
	/// <returns>A summary of applied consistency actions.</returns>
	public async Task<VaultAutoGeneratedPuckConsistencyResult> ReconcileAsync(CancellationToken cancellationToken = default)
	{
		var scanned = 0;
		var purged = 0;
		var renamed = 0;
		var alreadyTitleOnly = 0;

		// Authority outside a model's own granted roots derives only from a hosting entity that actually exists.
		// The hosting types are derived from the catalog (every distinct declared ParentEntityType), never
		// hard-coded, and their known ids are loaded once for the territory check below.
		var knownHostIdsByType = await LoadKnownHostIdsAsync(cancellationToken);

		foreach (var model in pathSyncModelCatalog.GetModels())
		{
			if (model.EntityType == typeof(LorePage))
			{
				continue;
			}

			var knownIds = await model.LoadKnownIdsAsync(context, cancellationToken);
			(scanned, purged, renamed, alreadyTitleOnly) = Aggregate(
				(scanned, purged, renamed, alreadyTitleOnly),
				await ProcessFilesAsync(EnumerateCandidateFiles(model), model, knownIds, knownHostIdsByType, cancellationToken));
		}

		return new VaultAutoGeneratedPuckConsistencyResult(scanned, purged, renamed, alreadyTitleOnly);
	}

	private static (int Scanned, int Purged, int Renamed, int AlreadyTitleOnly) Aggregate(
		(int Scanned, int Purged, int Renamed, int AlreadyTitleOnly) current,
		(int Scanned, int Purged, int Renamed, int AlreadyTitleOnly) next)
	{
		return (
			current.Scanned + next.Scanned,
			current.Purged + next.Purged,
			current.Renamed + next.Renamed,
			current.AlreadyTitleOnly + next.AlreadyTitleOnly);
	}

	private async Task<(int Scanned, int Purged, int Renamed, int AlreadyTitleOnly)> ProcessFilesAsync(
		IEnumerable<string> files,
		VaultPathSyncModel model,
		IReadOnlySet<string> knownIds,
		IReadOnlyDictionary<Type, HashSet<string>> knownHostIdsByType,
		CancellationToken cancellationToken)
	{
		var scanned = 0;
		var purged = 0;
		var renamed = 0;
		var alreadyTitleOnly = 0;

		foreach (var path in files)
		{
			cancellationToken.ThrowIfCancellationRequested();
			scanned++;
			var (id, title) = ResolvePathIdentity(model, path);
			if (id is null)
			{
				alreadyTitleOnly++;
				continue;
			}

			// Identity is notation-gated, never string-shaped: a filename prefix is an unknown-id entity file only
			// if it tokenizes against the entity's declared PUCK. A note whose name merely contains " - " (a date,
			// a counter, a topic) is the user's own file, not a desynced entity — leave it alone.
			if (!identityGate.IsMintable(model.EntityType, id))
			{
				continue;
			}

			if (knownIds.Contains(id))
			{
				continue;
			}

			// Authority is confined to declared territory. Outside the model's granted roots, a file is normalized
			// only when a known hosting entity (one that exists in the database) owns the location — never on the
			// strength of a path or filename shape alone.
			if (!IsWithinDeclaredTerritory(model, path, knownHostIdsByType))
			{
				continue;
			}

			if (policyEngine.PolicyFor(model.Mode).PurgesDesyncedFiles)
			{
				var archived = await ArchiveDeletionAsync(path, model.EntityName, id, title, "desync-purge", cancellationToken);
				await auditLogService.WriteAsync(
					"discovery",
					"desync-purge",
					subjectType: model.EntityName,
					subjectId: id,
					subjectTitle: title,
					temporalKind: "file",
					temporalEntryKey: archived?.EntryKey,
					temporalEntityType: model.EntityName,
					temporalEntityId: id,
					temporalEntityTitle: title,
					temporalLocation: archived?.ArchivedRelativePath,
					details: new { path },
					cancellationToken: cancellationToken);
				purged++;
				continue;
			}

			var result = await RenameWithoutIdAsync(path, model.EntityName, id, title, model.Shape == VaultStorageShape.SelfNamedDirectory, cancellationToken);
			if (result.Renamed)
			{
				await auditLogService.WriteAsync(
					"sync",
					result.Archived is null ? "strip-unknown-id" : "strip-unknown-id-conflict",
					subjectType: model.EntityName,
					subjectId: id,
					subjectTitle: title,
					temporalKind: result.Archived is null ? null : "file",
					temporalEntryKey: result.Archived?.EntryKey,
					temporalEntityType: result.Archived?.EntityType,
					temporalEntityId: result.Archived?.EntityId,
					temporalEntityTitle: result.Archived?.EntityTitle,
					temporalLocation: result.Archived?.ArchivedRelativePath,
					details: new { originalPath = path, result.NewPath },
					cancellationToken: cancellationToken);
				renamed++;
			}
		}

		return (scanned, purged, renamed, alreadyTitleOnly);
	}

	private (string? Id, string Title) ResolvePathIdentity(VaultPathSyncModel model, string path)
	{
		if (model.EntityType == typeof(LorePage))
		{
			var lorePage = new LorePage
			{
				Id = string.Empty,
				Title = string.Empty,
			};
			if (LorePage.TryApplyCompositionFromPath(lorePage, path, layout.VaultRoot, layout.SagaRoot)
				&& !string.IsNullOrWhiteSpace(lorePage.Id))
			{
				if (File.Exists(path))
				{
					var markdown = File.ReadAllText(path);
					markdownSerializer.DeserializePreservingDefaults(markdown, lorePage);
				}

				return (lorePage.Id, lorePage.Title);
			}
		}

		return PuckNamedIdentity.ParseLoosePath(path);
	}

	private IEnumerable<string> EnumerateCandidateFiles(VaultPathSyncModel model)
	{
		return pathSyncModelCatalog.EnumerateCandidateMarkdownPaths(model);
	}

	/// <summary>
	/// Loads the known identifiers of every distinct hosting (parent) entity type declared across the catalog, so
	/// the territory check can confirm a hosting entity actually exists without hard-coding any particular type.
	/// </summary>
	private async Task<IReadOnlyDictionary<Type, HashSet<string>>> LoadKnownHostIdsAsync(CancellationToken cancellationToken)
	{
		var hostTypes = entityModelCatalog.GetModels()
			.Select(model => model.Storage?.ParentEntityType)
			.Where(type => type is not null)
			.Distinct()
			.Cast<Type>();

		var result = new Dictionary<Type, HashSet<string>>();
		foreach (var hostType in hostTypes)
		{
			result[hostType] = await VaultEntityGateway.LoadKnownIdsAsync(context, hostType, cancellationToken);
		}

		return result;
	}

	/// <summary>
	/// Determines whether a candidate file sits within territory the model has been granted authority over: one of
	/// its specific (non-vault-root) scan roots, or a folder hosted by a parent entity that exists in the database.
	/// The whole-vault scan root is a detection net for identity-driven models, not a grant of authority, so a file
	/// reachable only through it belongs to the user unless a known hosting entity says otherwise.
	/// </summary>
	private bool IsWithinDeclaredTerritory(VaultPathSyncModel model, string path, IReadOnlyDictionary<Type, HashSet<string>> knownHostIdsByType)
	{
		var fullPath = Path.GetFullPath(path);
		var vaultRoot = Path.GetFullPath(layout.VaultRoot).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
		foreach (var root in model.ScanRoots)
		{
			var fullRoot = Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
			if (string.Equals(fullRoot, vaultRoot, StringComparison.OrdinalIgnoreCase))
			{
				continue;
			}

			if (fullPath.StartsWith(fullRoot + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}
		}

		// The hosting entity is resolved generically: the model's declared parent type, and the known ids of that
		// type. A file is in territory only when the resolved host actually exists in the database.
		var parentType = entityModelCatalog.TryGet(model.EntityType, out var declared)
			? declared.Storage?.ParentEntityType
			: null;
		if (parentType is null || !knownHostIdsByType.TryGetValue(parentType, out var knownHostIds))
		{
			return false;
		}

		return pathPolicy.EnumerateContainingParentIds(model.EntityType, fullPath).Any(knownHostIds.Contains);
	}

	private async Task<(bool Renamed, string? NewPath, FileGraveyardEntry? Archived)> RenameWithoutIdAsync(string path, string entityType, string id, string title, bool nestedFileMode, CancellationToken cancellationToken)
	{
		var titleOnlySegment = PuckNamedIdentity.FormatTitleOnlyFileName(title);
		if (nestedFileMode)
		{
			var currentDirectory = Path.GetDirectoryName(path)!;
			var parentDirectory = Directory.GetParent(currentDirectory)?.FullName;
			if (parentDirectory is null)
			{
				return (false, null, null);
			}

			var targetDirectory = Path.Combine(parentDirectory, titleOnlySegment);
			var targetFilePath = Path.Combine(targetDirectory, $"{titleOnlySegment}.md");
			return await MoveNestedFileAsync(path, currentDirectory, targetDirectory, targetFilePath, entityType, id, title, cancellationToken);
		}

		var flatTargetPath = Path.Combine(Path.GetDirectoryName(path)!, $"{titleOnlySegment}.md");
		if (string.Equals(path, flatTargetPath, StringComparison.OrdinalIgnoreCase))
		{
			return (false, null, null);
		}

		if (File.Exists(flatTargetPath))
		{
			var archived = await ArchiveDeletionAsync(path, entityType, id, title, "desync-conflict", cancellationToken);
			return (true, flatTargetPath, archived);
		}

		File.Move(path, flatTargetPath);
		return (true, flatTargetPath, null);
	}

	private async Task<(bool Renamed, string? NewPath, FileGraveyardEntry? Archived)> MoveNestedFileAsync(
		string currentFilePath,
		string currentDirectory,
		string targetDirectory,
		string targetFilePath,
		string entityType,
		string id,
		string title,
		CancellationToken cancellationToken)
	{
		if (string.Equals(currentDirectory, targetDirectory, StringComparison.OrdinalIgnoreCase)
			&& string.Equals(currentFilePath, targetFilePath, StringComparison.OrdinalIgnoreCase))
		{
			return (false, null, null);
		}

		if (Directory.Exists(targetDirectory))
		{
			if (File.Exists(targetFilePath))
			{
				var archived = await ArchiveDeletionAsync(currentDirectory, entityType, id, title, "desync-conflict", cancellationToken);
				PruneEmptyDirectories(currentDirectory);
				return (true, targetFilePath, archived);
			}

			Directory.CreateDirectory(targetDirectory);
			var tempPath = Path.Combine(targetDirectory, Path.GetFileName(currentFilePath));
			File.Move(currentFilePath, tempPath);
			File.Move(tempPath, targetFilePath);
			PruneEmptyDirectories(currentDirectory);
			return (true, targetFilePath, null);
		}

		Directory.Move(currentDirectory, targetDirectory);
		var movedPath = Path.Combine(targetDirectory, Path.GetFileName(currentFilePath));
		if (!string.Equals(movedPath, targetFilePath, StringComparison.OrdinalIgnoreCase))
		{
			File.Move(movedPath, targetFilePath);
		}

		return (true, targetFilePath, null);
	}

	private async Task<FileGraveyardEntry?> ArchiveDeletionAsync(string path, string entityType, string? entityId, string? entityTitle, string reason, CancellationToken cancellationToken)
	{
		var archiveTarget = ResolveArchiveTarget(path);
		if (archiveTarget is null)
		{
			return null;
		}

		var resolvedArchiveTarget = archiveTarget.Value;

		var cleanupRoot = resolvedArchiveTarget.IsDirectory
			? Directory.GetParent(resolvedArchiveTarget.Path)?.FullName
			: Path.GetDirectoryName(resolvedArchiveTarget.Path);

		var entry = await temporalDataService.ArchivePathAsync(
			resolvedArchiveTarget.Path,
			reason,
			entityType,
			entityId,
			entityTitle,
			Environment.UserName,
			cancellationToken);

		PruneEmptyDirectories(cleanupRoot);
		return entry;
	}

	private static (string Path, bool IsDirectory)? ResolveArchiveTarget(string path)
	{
		if (Directory.Exists(path))
		{
			return (path, true);
		}

		if (!File.Exists(path))
		{
			return null;
		}

		var directory = Path.GetDirectoryName(path)!;
		var selfNamedDirectory = string.Equals(Path.GetFileNameWithoutExtension(path), Path.GetFileName(directory), StringComparison.OrdinalIgnoreCase);
		return selfNamedDirectory && Directory.Exists(directory)
			? (directory, true)
			: (path, false);
	}

	private static void PruneEmptyDirectories(string? startDirectory)
	{
		var current = startDirectory;
		while (!string.IsNullOrWhiteSpace(current)
			&& Directory.Exists(current)
			&& !Directory.EnumerateFileSystemEntries(current).Any())
		{
			var parent = Directory.GetParent(current)?.FullName;
			Directory.Delete(current);
			current = parent;
		}
	}
}