using System.Reflection;
using Pleiades.Orchestration;
using Pleiades.Puck;
using Pleiades.Saga;
using Pleiades.Vault.Database;
using Pleiades.Vault.Watcher;

namespace Pleiades.Vault.Markdown;

/// <summary>
/// Reconciles vault-backed markdown files for entities whose PUCK identifiers are generated by the core.
/// </summary>
public sealed class VaultAutoGeneratedPuckConsistencyService(
	PlainfraContext context,
	VaultLayout layout,
	VaultPathSyncModelCatalog pathSyncModelCatalog,
	MarkdownFrontMatterSerializer markdownSerializer,
	VaultTemporalDataService temporalDataService,
	VaultAuditLogService auditLogService)
{
	/// <summary>
	/// Ensures stray user-created or desynchronized files are normalized according to the current storage policy.
	/// </summary>
	/// <returns>A summary of applied consistency actions.</returns>
	public async Task<VaultAutoGeneratedPuckConsistencyResult> ReconcileAsync(CancellationToken cancellationToken = default)
	{
		var scanned = 0;
		var purged = 0;
		var renamed = 0;
		var alreadyTitleOnly = 0;

		foreach (var model in pathSyncModelCatalog.GetModels())
		{
			if (model.EntityType == typeof(LorePage))
			{
				continue;
			}

			var knownIds = await model.LoadKnownIdsAsync(context, cancellationToken);
			(scanned, purged, renamed, alreadyTitleOnly) = Aggregate(
				(scanned, purged, renamed, alreadyTitleOnly),
				await ProcessFilesAsync(EnumerateCandidateFiles(model), model, knownIds, cancellationToken));
		}

		return new VaultAutoGeneratedPuckConsistencyResult(scanned, purged, renamed, alreadyTitleOnly);
	}

	private static (int Scanned, int Purged, int Renamed, int AlreadyTitleOnly) Aggregate(
		(int Scanned, int Purged, int Renamed, int AlreadyTitleOnly) current,
		(int Scanned, int Purged, int Renamed, int AlreadyTitleOnly) next)
	{
		return (
			current.Scanned + next.Scanned,
			current.Purged + next.Purged,
			current.Renamed + next.Renamed,
			current.AlreadyTitleOnly + next.AlreadyTitleOnly);
	}

	private async Task<(int Scanned, int Purged, int Renamed, int AlreadyTitleOnly)> ProcessFilesAsync(
		IEnumerable<string> files,
		VaultPathSyncModel model,
		IReadOnlySet<string> knownIds,
		CancellationToken cancellationToken)
	{
		var scanned = 0;
		var purged = 0;
		var renamed = 0;
		var alreadyTitleOnly = 0;

		foreach (var path in files)
		{
			cancellationToken.ThrowIfCancellationRequested();
			scanned++;
			var (id, title) = ResolvePathIdentity(model, path);
			if (id is null)
			{
				alreadyTitleOnly++;
				continue;
			}

			if (knownIds.Contains(id))
			{
				continue;
			}

			if (model.Mode == VaultStorageMode.Enforced)
			{
				var archived = await ArchiveDeletionAsync(path, model.EntityName, id, title, "desync-purge", cancellationToken);
				await auditLogService.WriteAsync(
					"discovery",
					"desync-purge",
					subjectType: model.EntityName,
					subjectId: id,
					subjectTitle: title,
					temporalKind: "file",
					temporalEntryKey: archived?.EntryKey,
					temporalEntityType: model.EntityName,
					temporalEntityId: id,
					temporalEntityTitle: title,
					temporalLocation: archived?.ArchivedRelativePath,
					details: new { path },
					cancellationToken: cancellationToken);
				purged++;
				continue;
			}

			var result = await RenameWithoutIdAsync(path, model.EntityName, id, title, model.Shape == VaultStorageShape.SelfNamedDirectory, cancellationToken);
			if (result.Renamed)
			{
				await auditLogService.WriteAsync(
					"sync",
					result.Archived is null ? "strip-unknown-id" : "strip-unknown-id-conflict",
					subjectType: model.EntityName,
					subjectId: id,
					subjectTitle: title,
					temporalKind: result.Archived is null ? null : "file",
					temporalEntryKey: result.Archived?.EntryKey,
					temporalEntityType: result.Archived?.EntityType,
					temporalEntityId: result.Archived?.EntityId,
					temporalEntityTitle: result.Archived?.EntityTitle,
					temporalLocation: result.Archived?.ArchivedRelativePath,
					details: new { originalPath = path, result.NewPath },
					cancellationToken: cancellationToken);
				renamed++;
			}
		}

		return (scanned, purged, renamed, alreadyTitleOnly);
	}

	private (string? Id, string Title) ResolvePathIdentity(VaultPathSyncModel model, string path)
	{
		if (model.EntityType == typeof(LorePage))
		{
			var lorePage = new LorePage
			{
				Id = string.Empty,
				Title = string.Empty,
			};
			if (LorePage.TryApplyCompositionFromPath(lorePage, path, layout.VaultRoot, layout.SagaRoot)
				&& !string.IsNullOrWhiteSpace(lorePage.Id))
			{
				if (File.Exists(path))
				{
					var markdown = File.ReadAllText(path);
					markdownSerializer.DeserializePreservingDefaults(markdown, lorePage);
				}

				return (lorePage.Id, lorePage.Title);
			}
		}

		return PuckNamedIdentity.ParseLoosePath(path);
	}

	private IEnumerable<string> EnumerateCandidateFiles(VaultPathSyncModel model)
	{
		return pathSyncModelCatalog.EnumerateCandidateMarkdownPaths(model);
	}

	private async Task<(bool Renamed, string? NewPath, FileGraveyardEntry? Archived)> RenameWithoutIdAsync(string path, string entityType, string id, string title, bool nestedFileMode, CancellationToken cancellationToken)
	{
		var titleOnlySegment = PuckNamedIdentity.FormatTitleOnlyFileName(title);
		if (nestedFileMode)
		{
			var currentDirectory = Path.GetDirectoryName(path)!;
			var parentDirectory = Directory.GetParent(currentDirectory)?.FullName;
			if (parentDirectory is null)
			{
				return (false, null, null);
			}

			var targetDirectory = Path.Combine(parentDirectory, titleOnlySegment);
			var targetFilePath = Path.Combine(targetDirectory, $"{titleOnlySegment}.md");
			return await MoveNestedFileAsync(path, currentDirectory, targetDirectory, targetFilePath, entityType, id, title, cancellationToken);
		}

		var flatTargetPath = Path.Combine(Path.GetDirectoryName(path)!, $"{titleOnlySegment}.md");
		if (string.Equals(path, flatTargetPath, StringComparison.OrdinalIgnoreCase))
		{
			return (false, null, null);
		}

		if (File.Exists(flatTargetPath))
		{
			var archived = await ArchiveDeletionAsync(path, entityType, id, title, "desync-conflict", cancellationToken);
			return (true, flatTargetPath, archived);
		}

		File.Move(path, flatTargetPath);
		return (true, flatTargetPath, null);
	}

	private async Task<(bool Renamed, string? NewPath, FileGraveyardEntry? Archived)> MoveNestedFileAsync(
		string currentFilePath,
		string currentDirectory,
		string targetDirectory,
		string targetFilePath,
		string entityType,
		string id,
		string title,
		CancellationToken cancellationToken)
	{
		if (string.Equals(currentDirectory, targetDirectory, StringComparison.OrdinalIgnoreCase)
			&& string.Equals(currentFilePath, targetFilePath, StringComparison.OrdinalIgnoreCase))
		{
			return (false, null, null);
		}

		if (Directory.Exists(targetDirectory))
		{
			if (File.Exists(targetFilePath))
			{
				var archived = await ArchiveDeletionAsync(currentDirectory, entityType, id, title, "desync-conflict", cancellationToken);
				PruneEmptyDirectories(currentDirectory);
				return (true, targetFilePath, archived);
			}

			Directory.CreateDirectory(targetDirectory);
			var tempPath = Path.Combine(targetDirectory, Path.GetFileName(currentFilePath));
			File.Move(currentFilePath, tempPath);
			File.Move(tempPath, targetFilePath);
			PruneEmptyDirectories(currentDirectory);
			return (true, targetFilePath, null);
		}

		Directory.Move(currentDirectory, targetDirectory);
		var movedPath = Path.Combine(targetDirectory, Path.GetFileName(currentFilePath));
		if (!string.Equals(movedPath, targetFilePath, StringComparison.OrdinalIgnoreCase))
		{
			File.Move(movedPath, targetFilePath);
		}

		return (true, targetFilePath, null);
	}

	private async Task<FileGraveyardEntry?> ArchiveDeletionAsync(string path, string entityType, string? entityId, string? entityTitle, string reason, CancellationToken cancellationToken)
	{
		var archiveTarget = ResolveArchiveTarget(path);
		if (archiveTarget is null)
		{
			return null;
		}

		var resolvedArchiveTarget = archiveTarget.Value;

		var cleanupRoot = resolvedArchiveTarget.IsDirectory
			? Directory.GetParent(resolvedArchiveTarget.Path)?.FullName
			: Path.GetDirectoryName(resolvedArchiveTarget.Path);

		var entry = await temporalDataService.ArchivePathAsync(
			resolvedArchiveTarget.Path,
			reason,
			entityType,
			entityId,
			entityTitle,
			Environment.UserName,
			cancellationToken);

		PruneEmptyDirectories(cleanupRoot);
		return entry;
	}

	private static (string Path, bool IsDirectory)? ResolveArchiveTarget(string path)
	{
		if (Directory.Exists(path))
		{
			return (path, true);
		}

		if (!File.Exists(path))
		{
			return null;
		}

		var directory = Path.GetDirectoryName(path)!;
		var selfNamedDirectory = string.Equals(Path.GetFileNameWithoutExtension(path), Path.GetFileName(directory), StringComparison.OrdinalIgnoreCase);
		return selfNamedDirectory && Directory.Exists(directory)
			? (directory, true)
			: (path, false);
	}

	private static void PruneEmptyDirectories(string? startDirectory)
	{
		var current = startDirectory;
		while (!string.IsNullOrWhiteSpace(current)
			&& Directory.Exists(current)
			&& !Directory.EnumerateFileSystemEntries(current).Any())
		{
			var parent = Directory.GetParent(current)?.FullName;
			Directory.Delete(current);
			current = parent;
		}
	}
}